### ISSUE TITLE
_id in the schema causing trouble?

### ISSUE THREAD

**Issue by benflinn** [cbargren/express-brute-mongoose#15]
I get this error:

Unhandled rejection MongoError: The field 'background' is not valid for an _id index specification. Specification: { v: 2, ns: "app.bruteforce", key: { _id: 1 }, name: "_id_1", background: true, unique: false }

but it goes away if I delete the _id field in the schema?

**Comment by benflinn** [comment]
also: this didn't happen before i updated mongoose to the latest version. went from mongoose 4.11.5  to 4.13.15

**Comment by Martii** [comment]
Doesn't seem to be present in *mongoose*@5.2.9 with our usage.

**Comment by cbargren** [comment]
Sorry for the long delay, haven't been watching this repo very closely.

This seems to be that you're defining an index on the `_id` field, which you shouldn't do: https://github.com/Automattic/mongoose/issues/5014 https://stackoverflow.com/questions/42378032/mongodb-3-4-2-invalidindexspecificationoption-error-the-field-unique-is-not-v/42383148

If that's not the case and you're still having this problem, reopen the ticket with the mongoose and mongodb versions you're having trouble with. Cheers!
