### ISSUE TITLE
Usage Question

### ISSUE THREAD

**Issue by AdventuresOfMar** [cbargren/express-brute-mongoose#6]
Hello, 

I'm new to nodejs and attempting to learn so I could easily be doing things wrong but how exactly do we check that this works? So far I've copied and pasted your sample code into my index.js changing the route to my "login" instead of "auth" and attempted making multiple api calls but I never get a 403 code kicked back. I also used robo mongo to check the DB for bruteforce collection entires but it's blank. Am I missing something?

**Comment by cbargren** [comment]
It sounds like you're on the right track for checking that it works. Are you looking in the right mongo collection? Are there any errors in your console while running?

Oh! I just noticed there's a typo in my sample code though on this line: 
```javascript
var bruteForceSchema = require('express-brute-mongoose/dist/schema');
```
`bruteForceSchema` should be capitalized. I'll fix that right now.

**Comment by AdventuresOfMar** [comment]
Hi @cbargren,

No worries, I corrected the typo in my original trial. The collection I'm checking is, "bruteForce" but sadly it's empty. Console logs that I'm currently checking are 1st. the original Db connection then I'm getting the http request call. Is there a way to check to see if brute force is being called? Or by chance do you have a sample project that I might learn from?

**Comment by cbargren** [comment]
Here are a couple things to check:
1. Make sure you're checking for your data in the right mongo database.
    - Use `show dbs` to view a list of your database names
    - Use `use <dbName>` to switch to the db that contains your data
    - Make sure you're looking at the right collection name with `db.getCollectionNames()`. Casing is important here. Then use `db.<collectionName>.find()` (the default collection name is `bruteforce`) to confirm that there are entries.
2. Try turning on [debug mode for mongoose](http://mongoosejs.com/docs/faq.html#enable_debugging) to see if any reads/writes are happening when you expect them to.

**Comment by cbargren** [comment]
The [readme](https://github.com/cbargren/express-brute-mongoose#readme) has a basic usage example, though I'm guessing that's what you're working off of... [This](https://github.com/Requarks/wiki/blob/9e801548e0424d0d02fc4c4afbcbc2014a24477b/server/controllers/auth.js#L17) repository has some example usage, though it doesn't seem to get any deeper than the Readme does. Hopefully that helps some.

**Comment by AdventuresOfMar** [comment]
Thanks so much! Checking into this tonight
