### ISSUE TITLE
Unhandled promise

### ISSUE THREAD

**Issue by kevinvugts** [cbargren/express-brute-mongoose#7]
Hi mate,

This doesn't work for node version 8.5.0. Could you please have a look into it?
It says that their is an unhandled promise. 

Thanks.

**Comment by cbargren** [comment]
Hey, thanks for the report. I'm not able to repro any trouble locally on Node v8.5.0 though. What versions of Mongoose and Mongo are you using and what Promise library are you plugging into Mongoose?

**Comment by cbargren** [comment]
If you're still experiencing issues, reopen this ticked with the above details. Thanks!
